apiVersion: v1
kind: Secret
metadata:
  name: tekton-basic-user-pass-git
  namespace: tekton-pipelines4
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: <cleartext non-encoded>
  password: <cleartext non-encoded>
