apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-and-push-run
  namespace: tekton-pipelines2
spec:
  serviceAccountName: build-sa 
  taskRef:
    name: build-and-push
  resources:
    inputs:
    - name: repo 
      resourceRef:
        name: qingjie-res